name: flutter_colorpicker
description: HSV(HSB)/HSL/RGB/Material color picker inspired by all the good design for your amazing flutter apps.
version: 1.0.4
homepage: https://github.com/raoulsson/flutter_colorpicker # forked from https://github.com/mchome/flutter_colorpicker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
